-- Importación de los 12 proyectos existentes (datos migrados desde data.js).
-- Las imágenes siguen apuntando a Cargo Collective; resúbelas desde el panel
-- cuando quieras independizarte de ese hosting.

insert into public.proyectos
  (slug, num, title, year, lugar, zona, edificio, arquitecto, cliente, programa, software, descripcion, tags, img_url)
values
  ('reforma-vivienda-madrid', 1, 'Reforma vivienda en Madrid', '2019', 'C/ Lope de Rueda, Madrid', NULL, NULL, NULL, 'Inversor', 'Reforma integral', NULL, 'Nos encontramos un piso de 1933 que apenas había sido intervenido desde su construcción. El trabajo realizado consistió en una reforma integral que recupera la lógica espacial original del edificio, actualizando instalaciones y acabados sin renunciar al carácter del inmueble.', '{"Reforma", "Madrid"}', 'https://payload.cargocollective.com/1/17/563714/12464303/prt_1546377373.jpg'),
  ('tfm', 2, 'TFM — Pabellón de España', '2018', 'Zaragoza', NULL, 'Pabellón de España', 'Patxi Mangado', NULL, NULL, 'Revit 2017', 'Trabajo Fin de Máster centrado en el modelado BIM del Pabellón de España, dirigido por Patxi Mangado. El proyecto profundiza en la metodología de modelado de información para edificación aplicada a un edificio de carácter institucional.', '{"TFM", "UPM", "BIM"}', 'https://payload.cargocollective.com/1/17/563714/13300401/prt_1514312588.jpg'),
  ('plaza-marques-de-salamanca', 3, 'Plaza Marqués de Salamanca', '2018', 'Madrid', NULL, 'Plaza Marqués de Salamanca, 11', NULL, NULL, NULL, NULL, 'Reportaje fotográfico de arquitectura realizado en el edificio número 11 de la Plaza Marqués de Salamanca, Madrid.', '{"Fotografía", "Madrid"}', 'https://payload.cargocollective.com/1/17/563714/13301387/prt_1514368912.jpg'),
  ('reforma-local-zaragoza', 4, 'Reforma local Zaragoza', '2017', 'Zaragoza', NULL, NULL, NULL, 'REDPISO Servicios Inmobiliarios', 'Oficina comercial para grupo inmobiliario-financiero', NULL, 'Reforma y obtención de licencia para una oficina comercial destinada a un grupo inmobiliario-financiero, adaptando el local a las necesidades de atención al público propias de la actividad.', '{"Reforma", "Zaragoza"}', 'https://payload.cargocollective.com/1/17/563714/12464309/prt_1486334549.jpg'),
  ('reforma-vivienda-zaragoza', 5, 'Reforma vivienda en Zaragoza', '2017', 'Zaragoza', NULL, NULL, NULL, 'Pareja joven', 'Reforma integral', NULL, 'Nos encontramos un piso de los años 70 completamente desactualizado en distribución e instalaciones. La reforma integral reorganiza la vivienda para adaptarla a las necesidades de una pareja joven, ganando luz y continuidad espacial.', '{"Reforma", "Zaragoza"}', 'https://payload.cargocollective.com/1/17/563714/11821910/prt_1486556150.jpg'),
  ('caixaforum', 6, 'CaixaForum', '2016', 'Zaragoza', NULL, 'CaixaForum', 'Carme Pinós', NULL, NULL, NULL, 'Reportaje fotográfico del edificio CaixaForum de Zaragoza, obra de la arquitecta Carme Pinós.', '{"Fotografía", "CaixaForum"}', 'https://payload.cargocollective.com/1/17/563714/12479067/prt_1486565025.jpg'),
  ('pfc', 7, 'PFC — Hotel, spa y parque ferroviario', '2016', 'Segovia', 'Antigua estación de ferrocarril', NULL, NULL, NULL, 'Hotel, spa y parque ferroviario', NULL, 'El proyecto nace de la mirada distraída del viajero sobre las infraestructuras ferroviarias en desuso. Propone la regeneración de la antigua estación de Segovia mediante un programa híbrido de hotel, spa y parque público que reactiva el lugar sin borrar su memoria industrial.', '{"PFC", "IE University"}', 'https://payload.cargocollective.com/1/17/563714/8826396/prt_1486386797.jpg'),
  ('edimburgo', 8, 'Edimburgo', '2015', 'Edimburgo', NULL, NULL, NULL, NULL, NULL, NULL, 'Serie fotográfica de arquitectura realizada durante un viaje a Edimburgo.', '{"Fotografía", "Edimburgo"}', 'https://payload.cargocollective.com/1/17/563714/12481279/prt_1486594873.jpg'),
  ('barcelona', 9, 'Barcelona — Plaça Sarrià', '2015', 'Barcelona', 'Plaça Sarrià', NULL, NULL, NULL, 'Biblioteca, archivo municipal y sede del distrito', NULL, 'Nuestra propuesta intenta conjugar el peso institucional del programa —biblioteca, archivo municipal y sede del distrito— con una escala doméstica que dialoga con el tejido residencial que rodea la plaza.', '{"Barcelona", "Concurso"}', 'https://payload.cargocollective.com/1/17/563714/8826403/prt_1486382275.jpg'),
  ('vallehermoso', 10, 'Vallehermoso', '2015', 'Madrid', 'Vallehermoso (Parcelas DS-2 y DS1-A)', NULL, NULL, NULL, 'Equipamiento deportivo y zona de oficinas', NULL, 'Se plantea un proyecto por fases para las parcelas DS-2 y DS1-A de Vallehermoso, combinando un equipamiento deportivo municipal con una zona de oficinas que activa el ámbito en distintos horarios del día.', '{"Vallehermoso", "Ayuntamiento de Madrid", "Concurso"}', 'https://payload.cargocollective.com/1/17/563714/8826384/prt_1486380594.jpg'),
  ('roquetas-de-mar', 11, 'Roquetas de Mar', '2014', 'Roquetas de Mar', 'Los Bajos', NULL, NULL, NULL, 'Regeneración del ámbito de las instalaciones de "Los Bajos"', NULL, 'Propuesta de regeneración del ámbito de las antiguas instalaciones de "Los Bajos" en Roquetas de Mar, reconvirtiendo el conjunto para un nuevo uso de carácter público.', '{"Roquetas de Mar", "Concurso"}', 'https://payload.cargocollective.com/1/17/563714/8826206/prt_1486335291.jpg'),
  ('lebbeus-woods', 12, 'Lebbeus Woods', '2014', 'Desconocido', 'Arquitectura de resistencia', NULL, NULL, NULL, 'Regeneración de espacios mediante sus propios materiales', NULL, '¿Qué vemos? Una mirada experimental sobre la arquitectura de resistencia de Lebbeus Woods: la regeneración de espacios dañados utilizando los propios materiales del lugar como herramienta de reconstrucción.', '{"Lebbeus Woods", "IE University"}', 'https://payload.cargocollective.com/1/17/563714/8826014/prt_1486296811.jpg');